### ISSUE TITLE
Script not working if folder name has space (" ")

### ISSUE THREAD

**Issue by VeikkoPeikko** [JerichoJones/JJ-s-XMR-STAK-HashRate-Monitor-and-Restart-Tool#2]
Thank you so much for such a great scrip!

I took it on a test ride today and had a minor difficulty to get it running. Script did not run directly in powershell but cmd worked just fine. It was unable to start again after hashrate drop. I found out that problem was in my folder name. It had a space in it. When I corrected folder path with no spaces in it everything is working flawlessly.

Maybe it should be stated in guide?

**Comment by JerichoJones** [comment]
Do you mean the parent folder has spaces?
If you added a path to the miner/tools that is not going to work based on how I parse the command line. I am new to Powershell so that was the best I could come up with. Maybe someone else can make some code suggestions. In any event, that is why it says:

# Expects to be in same folder as this script

I will add an explicit DO NOT DO THAT. This is the second time I have run into this so it seems like a good idea.

**Comment by VeikkoPeikko** [comment]
Yes, parent folder had a space in the folder name and script failed to restart.

**Comment by JerichoJones** [comment]
I think I see the problem (I hope anyway). I'll test it when I get home in a few hours.

**Comment by JerichoJones** [comment]
This turned out to be more difficult than I expected (for me anyway). It seems to be working so I'm going to test it overnight.

**Comment by JerichoJones** [comment]
Fix posted to dev branch.

**Comment by JerichoJones** [comment]
Fix posted to MASTER
